# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_final.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 294)
        Dialog.setStyleSheet("background-color: lightblue;")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(240, 130, 101, 41))
        self.pushButton.setStyleSheet("background-color: orange;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 130, 101, 41))
        self.pushButton_2.setStyleSheet("background-color: orange;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(70, 50, 101, 41))
        self.pushButton_3.setStyleSheet("background-color: green;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(240, 50, 101, 41))
        self.pushButton_4.setStyleSheet("background-color: red;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(150, 210, 101, 41))
        self.pushButton_5.setStyleSheet("background-color: lightgray;")
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Graficar"))
        self.pushButton_2.setText(_translate("Dialog", "Cargar csv"))
        self.pushButton_3.setText(_translate("Dialog", "Play"))
        self.pushButton_4.setText(_translate("Dialog", "Stop"))
        self.pushButton_5.setText(_translate("Dialog", "Calibración"))
